// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WebService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::thrift::webserver;

class WebServiceHandler : virtual public WebServiceIf {
 public:
  WebServiceHandler() {
    // Your initialization goes here
  }

  void read(ReadResult& _return, const ApiKey& apikey, const std::string& userkey, const std::string& query) {
    // Your implementation goes here
    printf("read\n");
  }

  void write(const ApiKey& apikey, const std::string& userkey, const std::string& data) {
    // Your implementation goes here
    printf("write\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<WebServiceHandler> handler(new WebServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new WebServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

